[tool.isort]
force_sort_within_sections = true
combine_as_imports = true
line_length = 100
balanced_wrapping = true
use_parentheses = true
include_trailing_comma = true
skip = ["lib", "bin"]

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_incomplete_stub = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_return_any = true
warn_unreachable = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true

[tool.pytest.ini_options]
testpaths = ["tests"]